GET http://127.0.0.1:5000/messages

###

POST http://127.0.0.1:5000/messages
Content-Type: application/json

{
  "textOfMessage": "Good luck",
  "emailOfAutor": "test4@test.test"
}

###
GET http://127.0.0.1:5000/messages/1ae41fa2-02f5-47be-b091-3db24aea2bca

###
DELETE http://127.0.0.1:5000/messages/5535dfb7-f1f0-48bc-80f8-9109a870451d

###
PATCH http://127.0.0.1:5000/messages/842cd259-e9bf-4a4b-aacd-3b329258afc7
Content-Type: application/json

{
  "textOfMessage": "Bye-bye"
}



