GET http://127.0.0.1:5000/messages

###

POST http://127.0.0.1:5000/messages
Content-Type: application/json

{
  "textOfMessage": "Good luck",
  "emailOfAutor": "test4@test.test"
}

###
GET http://127.0.0.1:5000/messages/eb342812-dcb5-47e6-94fc-00be173e481c

###
DELETE http://127.0.0.1:5000/messages/a551bd07-b095-4e90-8920-5cba67b882dc

###
PATCH http://127.0.0.1:5000/messages/9afb4fa4-7ce2-4998-b04a-462ea1a7b1ce
Content-Type: application/json

{
  "textOfMessage": "Bye-bye"
}



